import subprocess
import matplotlib.pyplot as plt
import numpy as np
subprocess.call("scp pi:satellites-teensyMasterSlave/log.csv .", shell=True)
csv_string = np.array([[int(x, 16) for x in line.split(',')] for line in open("log.csv")])
for i in range(4):
    print("Axis", i)
    plt.plot(csv_string[:, i], label="ADC")
    plt.plot(csv_string[:, 4 + i], label="INCOHERENT")
    plt.plot(csv_string[:, 8 + i], label="PID")
    plt.legend()
    plt.show()
print("ADC")
plt.plot(csv_string[:, 0], label='0')
plt.plot(csv_string[:, 1], label='1')
plt.plot(csv_string[:, 2], label='2')
plt.plot(csv_string[:, 3], label='3')
plt.legend()
plt.show()
print("Incoherent")
plt.plot(csv_string[:, 4], label='0')
plt.plot(csv_string[:, 5], label='1')
plt.plot(csv_string[:, 6], label='2')
plt.plot(csv_string[:, 7], label='3')
plt.legend()
plt.show()
print("Pid")
plt.plot(csv_string[:, 8], label='0')
plt.plot(csv_string[:, 9], label='1')
plt.plot(csv_string[:, 10], label='2')
plt.plot(csv_string[:, 11], label='3')
plt.legend()
plt.show()

