#!/usr/bin/env python
import os.path
import re
import sys

hostname = 'pi'
home = os.path.expanduser('~')
sshconfig = os.path.join(home, '.ssh', 'config')

def replacePort(port, path):
    with open(sshconfig, 'r') as f:
        lines = f.read().splitlines()

    reachedHost = False
    for i in range(len(lines)):
        line = lines[i]
        if reachedHost:
            if line.strip().startswith('Host '):
                break
            else:
                new_line = 'Port ' + str(port)
                lines[i] = re.sub('Port \d+', new_line, line)
        if line.strip() == 'Host pi':
            reachedHost = True  
                
    with open(sshconfig, 'w') as f:
        f.write('\n'.join(lines))


if len(sys.argv) == 1:
    print("Please supply the port number")
else:
    port = int(sys.argv[1])
    replacePort(port, sshconfig)
