#!/usr/bin/python
import os
import sys
import subprocess

try:
    serial_number = sys.argv[1]
except:
    serial_number = '0'

subprocess.call("pio device monitor --port=/dev/ttyACM" + serial_number + " | tee " + serial_number + ".log", shell=True)
